SELECT BRAND,SEGMENT,SUM(QUANTITY) FROM SALES GROUP BY BRAND,SEGMENT 
UNION ALL 
SELECT BRAND,NULL, SUM(QUANTITY) FROM SALES GROUP BY BRAND
UNION ALL 
SELECT NULL, SEGMENT, SUM(QUANTITY) FROM SALES GROUP BY SEGMENT
UNION ALL 
SELECT NULL,NULL,SUM(QUANTITY) FROM SALES ;